# Generated by Django 4.0.3 on 2023-03-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='customer',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
